/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IAlbumPersonList
 */
export interface IAlbumPersonList {
    /**
     * 
     * @type {string}
     * @memberof IAlbumPersonList
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof IAlbumPersonList
     */
    'photo_count': string;
    /**
     * 
     * @type {string}
     * @memberof IAlbumPersonList
     */
    'cover_photo_url': string;
    /**
     * 
     * @type {number}
     * @memberof IAlbumPersonList
     */
    'id': number;
}

