/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IPhotoHashList } from './iphoto-hash-list';
import { ISimpleUser } from './isimple-user';

/**
 * 
 * @export
 * @interface IAlbumUserList
 */
export interface IAlbumUserList {
    /**
     * 
     * @type {number}
     * @memberof IAlbumUserList
     */
    'id': number;
    /**
     * 
     * @type {Array<IPhotoHashList>}
     * @memberof IAlbumUserList
     */
    'cover_photos': Array<IPhotoHashList>;
    /**
     * 
     * @type {string}
     * @memberof IAlbumUserList
     */
    'created_on': string;
    /**
     * 
     * @type {boolean}
     * @memberof IAlbumUserList
     */
    'favorited'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IAlbumUserList
     */
    'title': string;
    /**
     * 
     * @type {Array<ISimpleUser>}
     * @memberof IAlbumUserList
     */
    'shared_to': Array<ISimpleUser>;
    /**
     * 
     * @type {ISimpleUser}
     * @memberof IAlbumUserList
     */
    'owner': ISimpleUser;
    /**
     * 
     * @type {string}
     * @memberof IAlbumUserList
     */
    'photo_count': string;
}

