/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IPhotoSuperSimple } from './iphoto-super-simple';

/**
 * 
 * @export
 * @interface IAlbumThing
 */
export interface IAlbumThing {
    /**
     * 
     * @type {number}
     * @memberof IAlbumThing
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof IAlbumThing
     */
    'title': string;
    /**
     * 
     * @type {Array<IPhotoSuperSimple>}
     * @memberof IAlbumThing
     */
    'photos': Array<IPhotoSuperSimple>;
}

