/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IPhotoHashList } from './iphoto-hash-list';

/**
 * 
 * @export
 * @interface IAlbumThingList
 */
export interface IAlbumThingList {
    /**
     * 
     * @type {number}
     * @memberof IAlbumThingList
     */
    'id': number;
    /**
     * 
     * @type {Array<IPhotoHashList>}
     * @memberof IAlbumThingList
     */
    'cover_photos': Array<IPhotoHashList>;
    /**
     * 
     * @type {string}
     * @memberof IAlbumThingList
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof IAlbumThingList
     */
    'photo_count': string;
}

