/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IAlbumAutoList
 */
export interface IAlbumAutoList {
    /**
     * 
     * @type {number}
     * @memberof IAlbumAutoList
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof IAlbumAutoList
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IAlbumAutoList
     */
    'timestamp': string;
    /**
     * 
     * @type {string}
     * @memberof IAlbumAutoList
     */
    'photos': string;
    /**
     * 
     * @type {string}
     * @memberof IAlbumAutoList
     */
    'photo_count': string;
    /**
     * 
     * @type {boolean}
     * @memberof IAlbumAutoList
     */
    'favorited'?: boolean;
}

