/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IPerson } from './iperson';

/**
 * 
 * @export
 * @interface IFace
 */
export interface IFace {
    /**
     * 
     * @type {number}
     * @memberof IFace
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof IFace
     */
    'face_url': string;
    /**
     * 
     * @type {string}
     * @memberof IFace
     */
    'photo_id': string | null;
    /**
     * 
     * @type {IPerson}
     * @memberof IFace
     */
    'person': IPerson;
    /**
     * 
     * @type {number}
     * @memberof IFace
     */
    'person_id': number;
    /**
     * 
     * @type {boolean}
     * @memberof IFace
     */
    'person_label_is_inferred'?: boolean | null;
}

