/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IInlineResponse200
 */
export interface IInlineResponse200 {
    /**
     * 
     * @type {number}
     * @memberof IInlineResponse200
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IInlineResponse200
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IInlineResponse200
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof IInlineResponse200
     */
    'results'?: Array<{ [key: string]: any; }>;
}

