/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IJobTypeEnum } from './ijob-type-enum';
import { ISimpleUser } from './isimple-user';

/**
 * 
 * @export
 * @interface ILongRunningJob
 */
export interface ILongRunningJob {
    /**
     * 
     * @type {string}
     * @memberof ILongRunningJob
     */
    'job_id': string;
    /**
     * 
     * @type {string}
     * @memberof ILongRunningJob
     */
    'queued_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ILongRunningJob
     */
    'finished'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ILongRunningJob
     */
    'finished_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ILongRunningJob
     */
    'started_at'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ILongRunningJob
     */
    'failed'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ILongRunningJob
     */
    'job_type_str': string;
    /**
     * 
     * @type {IJobTypeEnum}
     * @memberof ILongRunningJob
     */
    'job_type': IJobTypeEnum;
    /**
     * 
     * @type {ISimpleUser}
     * @memberof ILongRunningJob
     */
    'started_by': ISimpleUser;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ILongRunningJob
     */
    'result'?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof ILongRunningJob
     */
    'id': number;
}

