/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IAlbumThing } from './ialbum-thing';

/**
 * 
 * @export
 * @interface IPaginatedAlbumThingList
 */
export interface IPaginatedAlbumThingList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedAlbumThingList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumThingList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumThingList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IAlbumThing>}
     * @memberof IPaginatedAlbumThingList
     */
    'results'?: Array<IAlbumThing>;
}

