/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IPerson } from './iperson';

/**
 * 
 * @export
 * @interface IPaginatedPersonList
 */
export interface IPaginatedPersonList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedPersonList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedPersonList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedPersonList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IPerson>}
     * @memberof IPaginatedPersonList
     */
    'results'?: Array<IPerson>;
}

