/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IAlbumPlace } from './ialbum-place';

/**
 * 
 * @export
 * @interface IPaginatedAlbumPlaceList
 */
export interface IPaginatedAlbumPlaceList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedAlbumPlaceList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumPlaceList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumPlaceList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IAlbumPlace>}
     * @memberof IPaginatedAlbumPlaceList
     */
    'results'?: Array<IAlbumPlace>;
}

