/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ILongRunningJob } from './ilong-running-job';

/**
 * 
 * @export
 * @interface IPaginatedLongRunningJobList
 */
export interface IPaginatedLongRunningJobList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedLongRunningJobList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedLongRunningJobList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedLongRunningJobList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<ILongRunningJob>}
     * @memberof IPaginatedLongRunningJobList
     */
    'results'?: Array<ILongRunningJob>;
}

