/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IPhotoSimple } from './iphoto-simple';

/**
 * 
 * @export
 * @interface IPaginatedPhotoSimpleList
 */
export interface IPaginatedPhotoSimpleList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedPhotoSimpleList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedPhotoSimpleList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedPhotoSimpleList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IPhotoSimple>}
     * @memberof IPaginatedPhotoSimpleList
     */
    'results'?: Array<IPhotoSimple>;
}

