/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IUser } from './iuser';

/**
 * 
 * @export
 * @interface IPaginatedUserList
 */
export interface IPaginatedUserList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedUserList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedUserList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedUserList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IUser>}
     * @memberof IPaginatedUserList
     */
    'results'?: Array<IUser>;
}

