/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IPhoto } from './iphoto';

/**
 * 
 * @export
 * @interface IPaginatedPhotoList
 */
export interface IPaginatedPhotoList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedPhotoList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedPhotoList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedPhotoList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IPhoto>}
     * @memberof IPaginatedPhotoList
     */
    'results'?: Array<IPhoto>;
}

