/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ISharedFromMePhotoThrough } from './ishared-from-me-photo-through';

/**
 * 
 * @export
 * @interface IPaginatedSharedFromMePhotoThroughList
 */
export interface IPaginatedSharedFromMePhotoThroughList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedSharedFromMePhotoThroughList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedSharedFromMePhotoThroughList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedSharedFromMePhotoThroughList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<ISharedFromMePhotoThrough>}
     * @memberof IPaginatedSharedFromMePhotoThroughList
     */
    'results'?: Array<ISharedFromMePhotoThrough>;
}

