/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IAlbumAuto } from './ialbum-auto';

/**
 * 
 * @export
 * @interface IPaginatedAlbumAutoList
 */
export interface IPaginatedAlbumAutoList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedAlbumAutoList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumAutoList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumAutoList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IAlbumAuto>}
     * @memberof IPaginatedAlbumAutoList
     */
    'results'?: Array<IAlbumAuto>;
}

