/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IAlbumThingList } from './ialbum-thing-list';

/**
 * 
 * @export
 * @interface IPaginatedAlbumThingListList
 */
export interface IPaginatedAlbumThingListList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedAlbumThingListList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumThingListList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumThingListList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IAlbumThingList>}
     * @memberof IPaginatedAlbumThingListList
     */
    'results'?: Array<IAlbumThingList>;
}

