/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IAlbumPersonList } from './ialbum-person-list';

/**
 * 
 * @export
 * @interface IPaginatedAlbumPersonListList
 */
export interface IPaginatedAlbumPersonListList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedAlbumPersonListList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumPersonListList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumPersonListList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IAlbumPersonList>}
     * @memberof IPaginatedAlbumPersonListList
     */
    'results'?: Array<IAlbumPersonList>;
}

