/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IFaceList } from './iface-list';

/**
 * 
 * @export
 * @interface IPaginatedFaceListList
 */
export interface IPaginatedFaceListList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedFaceListList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedFaceListList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedFaceListList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IFaceList>}
     * @memberof IPaginatedFaceListList
     */
    'results'?: Array<IFaceList>;
}

