/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IManageUser } from './imanage-user';

/**
 * 
 * @export
 * @interface IPaginatedManageUserList
 */
export interface IPaginatedManageUserList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedManageUserList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedManageUserList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedManageUserList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IManageUser>}
     * @memberof IPaginatedManageUserList
     */
    'results'?: Array<IManageUser>;
}

