/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IAlbumUserList } from './ialbum-user-list';

/**
 * 
 * @export
 * @interface IPaginatedAlbumUserListList
 */
export interface IPaginatedAlbumUserListList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedAlbumUserListList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumUserListList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumUserListList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IAlbumUserList>}
     * @memberof IPaginatedAlbumUserListList
     */
    'results'?: Array<IAlbumUserList>;
}

