/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IAlbumUserEdit } from './ialbum-user-edit';

/**
 * 
 * @export
 * @interface IPaginatedAlbumUserEditList
 */
export interface IPaginatedAlbumUserEditList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedAlbumUserEditList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumUserEditList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumUserEditList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IAlbumUserEdit>}
     * @memberof IPaginatedAlbumUserEditList
     */
    'results'?: Array<IAlbumUserEdit>;
}

