/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IAlbumAutoList } from './ialbum-auto-list';

/**
 * 
 * @export
 * @interface IPaginatedAlbumAutoListList
 */
export interface IPaginatedAlbumAutoListList {
    /**
     * 
     * @type {number}
     * @memberof IPaginatedAlbumAutoListList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumAutoListList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPaginatedAlbumAutoListList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<IAlbumAutoList>}
     * @memberof IPaginatedAlbumAutoListList
     */
    'results'?: Array<IAlbumAutoList>;
}

