/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ISaveMetadataToDiskEnum } from './isave-metadata-to-disk-enum';

/**
 * 
 * @export
 * @interface IPatchedManageUser
 */
export interface IPatchedManageUser {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof IPatchedManageUser
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedManageUser
     */
    'scan_directory'?: string;
    /**
     * 
     * @type {number}
     * @memberof IPatchedManageUser
     */
    'confidence'?: number;
    /**
     * 
     * @type {number}
     * @memberof IPatchedManageUser
     */
    'semantic_search_topk'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPatchedManageUser
     */
    'last_login'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPatchedManageUser
     */
    'date_joined'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedManageUser
     */
    'photo_count'?: string;
    /**
     * 
     * @type {number}
     * @memberof IPatchedManageUser
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof IPatchedManageUser
     */
    'favorite_min_rating'?: number;
    /**
     * 
     * @type {number}
     * @memberof IPatchedManageUser
     */
    'image_scale'?: number;
    /**
     * 
     * @type {ISaveMetadataToDiskEnum}
     * @memberof IPatchedManageUser
     */
    'save_metadata_to_disk'?: ISaveMetadataToDiskEnum;
}

