/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IPatchedAlbumUserEdit
 */
export interface IPatchedAlbumUserEdit {
    /**
     * 
     * @type {number}
     * @memberof IPatchedAlbumUserEdit
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumUserEdit
     */
    'title'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IPatchedAlbumUserEdit
     */
    'photos'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumUserEdit
     */
    'created_on'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IPatchedAlbumUserEdit
     */
    'favorited'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof IPatchedAlbumUserEdit
     */
    'removedPhotos'?: Array<string>;
}

