/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IPatchedAlbumAutoList
 */
export interface IPatchedAlbumAutoList {
    /**
     * 
     * @type {number}
     * @memberof IPatchedAlbumAutoList
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumAutoList
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumAutoList
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumAutoList
     */
    'photos'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumAutoList
     */
    'photo_count'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IPatchedAlbumAutoList
     */
    'favorited'?: boolean;
}

