/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IPhotoSimple } from './iphoto-simple';

/**
 * 
 * @export
 * @interface IPatchedAlbumAuto
 */
export interface IPatchedAlbumAuto {
    /**
     * 
     * @type {number}
     * @memberof IPatchedAlbumAuto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumAuto
     */
    'title'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IPatchedAlbumAuto
     */
    'favorited'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumAuto
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumAuto
     */
    'created_on'?: string;
    /**
     * 
     * @type {number}
     * @memberof IPatchedAlbumAuto
     */
    'gps_lat'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumAuto
     */
    'people'?: string;
    /**
     * 
     * @type {number}
     * @memberof IPatchedAlbumAuto
     */
    'gps_lon'?: number | null;
    /**
     * 
     * @type {Array<IPhotoSimple>}
     * @memberof IPatchedAlbumAuto
     */
    'photos'?: Array<IPhotoSimple>;
}

