/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IPhotoHashList } from './iphoto-hash-list';
import { ISimpleUser } from './isimple-user';

/**
 * 
 * @export
 * @interface IPatchedAlbumUserList
 */
export interface IPatchedAlbumUserList {
    /**
     * 
     * @type {number}
     * @memberof IPatchedAlbumUserList
     */
    'id'?: number;
    /**
     * 
     * @type {Array<IPhotoHashList>}
     * @memberof IPatchedAlbumUserList
     */
    'cover_photos'?: Array<IPhotoHashList>;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumUserList
     */
    'created_on'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IPatchedAlbumUserList
     */
    'favorited'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumUserList
     */
    'title'?: string;
    /**
     * 
     * @type {Array<ISimpleUser>}
     * @memberof IPatchedAlbumUserList
     */
    'shared_to'?: Array<ISimpleUser>;
    /**
     * 
     * @type {ISimpleUser}
     * @memberof IPatchedAlbumUserList
     */
    'owner'?: ISimpleUser;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumUserList
     */
    'photo_count'?: string;
}

