/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IPatchedAlbumPersonList
 */
export interface IPatchedAlbumPersonList {
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumPersonList
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumPersonList
     */
    'photo_count'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumPersonList
     */
    'cover_photo_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof IPatchedAlbumPersonList
     */
    'id'?: number;
}

