/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IPhotoHashList } from './iphoto-hash-list';

/**
 * 
 * @export
 * @interface IPatchedAlbumPlaceList
 */
export interface IPatchedAlbumPlaceList {
    /**
     * 
     * @type {number}
     * @memberof IPatchedAlbumPlaceList
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof IPatchedAlbumPlaceList
     */
    'geolocation_level'?: number | null;
    /**
     * 
     * @type {Array<IPhotoHashList>}
     * @memberof IPatchedAlbumPlaceList
     */
    'cover_photos'?: Array<IPhotoHashList>;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumPlaceList
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedAlbumPlaceList
     */
    'photo_count'?: string;
}

