/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IPatchedFaceList
 */
export interface IPatchedFaceList {
    /**
     * 
     * @type {number}
     * @memberof IPatchedFaceList
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPatchedFaceList
     */
    'image'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPatchedFaceList
     */
    'photo'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof IPatchedFaceList
     */
    'person'?: number;
    /**
     * 
     * @type {number}
     * @memberof IPatchedFaceList
     */
    'person_label_probability'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPatchedFaceList
     */
    'person_name'?: string;
}

