/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IPatchedPerson
 */
export interface IPatchedPerson {
    /**
     * 
     * @type {string}
     * @memberof IPatchedPerson
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedPerson
     */
    'face_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedPerson
     */
    'face_count'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedPerson
     */
    'face_photo_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedPerson
     */
    'video'?: string;
    /**
     * 
     * @type {number}
     * @memberof IPatchedPerson
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof IPatchedPerson
     */
    'newPersonName'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPatchedPerson
     */
    'cover_photo'?: string;
}

