/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IPatchedPhotoEdit
 */
export interface IPatchedPhotoEdit {
    /**
     * 
     * @type {string}
     * @memberof IPatchedPhotoEdit
     */
    'image_hash'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IPatchedPhotoEdit
     */
    'hidden'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof IPatchedPhotoEdit
     */
    'rating'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof IPatchedPhotoEdit
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IPatchedPhotoEdit
     */
    'video'?: boolean;
}

