/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IPerson
 */
export interface IPerson {
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    'face_url': string;
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    'face_count': string;
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    'face_photo_url': string;
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    'video': string;
    /**
     * 
     * @type {number}
     * @memberof IPerson
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    'newPersonName'?: string;
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    'cover_photo'?: string;
}

