/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IPhotoHashList
 */
export interface IPhotoHashList {
    /**
     * 
     * @type {string}
     * @memberof IPhotoHashList
     */
    'image_hash': string;
    /**
     * 
     * @type {boolean}
     * @memberof IPhotoHashList
     */
    'video'?: boolean;
}

