/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IPhoto
 */
export interface IPhoto {
    /**
     * 
     * @type {number}
     * @memberof IPhoto
     */
    'exif_gps_lat'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IPhoto
     */
    'exif_gps_lon'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'exif_timestamp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'search_captions'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'search_location'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'captions_json': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'thumbnail_url': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'thumbnail_height': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'thumbnail_width': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'small_thumbnail_url': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'big_thumbnail_url': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'square_thumbnail_url': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'big_square_thumbnail_url': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'small_square_thumbnail_url': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'tiny_square_thumbnail_url': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IPhoto
     */
    'geolocation_json'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IPhoto
     */
    'exif_json'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'people': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'image_url': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'image_hash': string;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'image_path': string;
    /**
     * 
     * @type {number}
     * @memberof IPhoto
     */
    'rating'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof IPhoto
     */
    'hidden'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IPhoto
     */
    'public'?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof IPhoto
     */
    'shared_to': Array<number>;
    /**
     * 
     * @type {string}
     * @memberof IPhoto
     */
    'similar_photos': string;
    /**
     * 
     * @type {boolean}
     * @memberof IPhoto
     */
    'video'?: boolean;
}

