/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IPhotoEdit
 */
export interface IPhotoEdit {
    /**
     * 
     * @type {string}
     * @memberof IPhotoEdit
     */
    'image_hash': string;
    /**
     * 
     * @type {boolean}
     * @memberof IPhotoEdit
     */
    'hidden'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof IPhotoEdit
     */
    'rating'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof IPhotoEdit
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IPhotoEdit
     */
    'video'?: boolean;
}

