/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ISaveMetadataToDiskEnum = {
    Off: 'OFF',
    MediaFile: 'MEDIA_FILE',
    SidecarFile: 'SIDECAR_FILE'
} as const;

export type ISaveMetadataToDiskEnum = typeof ISaveMetadataToDiskEnum[keyof typeof ISaveMetadataToDiskEnum];



