/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ISimpleUser
 */
export interface ISimpleUser {
    /**
     * 
     * @type {number}
     * @memberof ISimpleUser
     */
    'id': number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof ISimpleUser
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof ISimpleUser
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ISimpleUser
     */
    'last_name'?: string;
}

