/* tslint:disable */
/* eslint-disable */
/**
 * LibrePhotos
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IDefaultTimezoneEnum } from './idefault-timezone-enum';
import { ISaveMetadataToDiskEnum } from './isave-metadata-to-disk-enum';

/**
 * 
 * @export
 * @interface IUser
 */
export interface IUser {
    /**
     * 
     * @type {number}
     * @memberof IUser
     */
    'id': number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof IUser
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'scan_directory'?: string;
    /**
     * 
     * @type {number}
     * @memberof IUser
     */
    'confidence'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof IUser
     */
    'transcode_videos'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof IUser
     */
    'semantic_search_topk'?: number;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'public_photo_samples': string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'public_photo_count': string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'date_joined'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'avatar'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'photo_count': string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'nextcloud_server_address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'nextcloud_username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'nextcloud_app_password'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'nextcloud_scan_directory'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'avatar_url': string;
    /**
     * 
     * @type {number}
     * @memberof IUser
     */
    'favorite_min_rating'?: number;
    /**
     * 
     * @type {number}
     * @memberof IUser
     */
    'image_scale'?: number;
    /**
     * 
     * @type {ISaveMetadataToDiskEnum}
     * @memberof IUser
     */
    'save_metadata_to_disk'?: ISaveMetadataToDiskEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IUser
     */
    'datetime_rules'?: { [key: string]: any; };
    /**
     * 
     * @type {IDefaultTimezoneEnum}
     * @memberof IUser
     */
    'default_timezone'?: IDefaultTimezoneEnum;
}

